#!/bin/bash
# command line build script for building release version
# This will only work on my (Jack Palevich) computer, because it
# requires the private key store used to sign the release version
# of Terminal Emulator for Android.
set -e

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
ATE_ROOT="$( cd $DIR/.. && pwd )"

cd "$ATE_ROOT"

if [ ! -f "local.properties" ]; then
    echo "local.properties does not exist. Please create it."
    exit 1
fi

./gradlew assembleRelease && ./tools/sign-release-build
