#!/bin/bash
# command line build script for installing required SDK packages.
set -e

if [ -z "${ANDROID_SDK_ROOT+xxx}" ]; then
    echo "Please define ANDROID_SDK_ROOT to point to the Android SDK"
    exit 1
fi

if [ ! -d "$ANDROID_SDK_ROOT" ]; then
    echo "The directory $ANDROID_SDK_ROOT = ${ANDROID_SDK_ROOT} does not exist."
    exit 1
fi

ANDROID="$ANDROID_SDK_ROOT/tools/android"

for i in android-11; do
  $ANDROID update sdk -u -a -t "$i"
done
