#!/bin/bash
# command line build script for installing and running terminal emulator.
adb uninstall jackpal.androidterm
adb install -r bin/Term-debug.apk && adb shell am start -n jackpal.androidterm/jackpal.androidterm.Term
